### ISSUE TITLE
Ways to display a time table?

### ISSUE THREAD

**Issue by philippbayer** [resbaz/resbaz2018#6]
Currently the Perth page displays a preliminary time table using the csv import function.
The problem is that this duplicates data a little bit - I would love if we could somehow use the short descriptions for the workshops and link these into the time table. Is there a predefined structure for that? Then we'd have less duplicated data

**Comment by amandamiotto** [comment]
How did you go with this?

**Comment by philippbayer** [comment]
In the end, we used the community_day.csv template to make the entire time table, see https://resbaz.github.io/resbaz2018/perth/
