### ISSUE TITLE
ResBaz 2019?

### ISSUE THREAD

**Issue by drmowinckels** [resbaz/resbaz2018#99]
Hey! When can we expect repos for 2019 to be initiated? Oslo ResBaz is planning to have their week as the first week of 2019, to grab rooms before standard courses start.

**Comment by amandamiotto** [comment]
I'll do a shout on the resbaz slack for you (are you on that?) and see if there's an official organizer or if its just a job that needs doing.

**Comment by drmowinckels** [comment]
i didnt know there was one! awesome if you can ask :)

**Comment by amandamiotto** [comment]
https://resbaz-team.slack.com I did mention it. I can accept a pull request if you want to do it this way.

**Comment by DamienIrving** [comment]
@Athanasiamo Apologies for the delay in responding. I'll get a 2019 website (and associated GitHub repo) up this week 😄

**Comment by drmowinckels** [comment]
@DamienIrving that awesome!

**Comment by ccronje** [comment]
Thanks @DamienIrving - for new folks the 2019 repo is here https://github.com/resbaz/resbaz2019
